export const SET_LOGIN_MODAL_VISIBILITY = "SET_LOGIN_MODAL_VISIBILITY";
export const SET_REGISTER_MODAL_VISIBILITY = "SET_REGISTER_MODAL_VISIBILITY";
export const SET_BILL_MODAL_VISIBILITY = "SET_BILL_MODAL_VISIBILITY";
export const SET_INSERT_MESSAGE_FORM_VISIBILITY =
  "SET_INSERT_MESSAGE_FORM_VISIBILITY";
