export const FETCH_THE_LATEST_POLL = "FETCH_THE_LATEST_POLL";
export const CHECK_IS_USER_VOTED_ON_POLL = "CHECK_IS_USER_VOTED_ON_POLL";
export const FETCH_NUMBER_OF_VOTERS_FOR_POLL_OPTIONS =
  "FETCH_NUMBER_OF_VOTERS_FOR_POLL_OPTIONS";
export const INCREASE_NUMBER_OF_VOTERS_FOR_POLL =
  "INCREASE_NUMBER_OF_VOTERS_FOR_POLL";
