export const FETCH_USER_BY_ID = "FETCH_USER_BY_ID";
export const INSERT_USER = "INSERT_USER";
export const FETCH_PACKET_COMBINATION_BY_PACKET_IDS =
  "FETCH_PACKET_COMBINATION_BY_PACKET_IDS";
export const UPDATE_USER_IMAGE = "UPDATE_USER_IMAGE";
