export const FETCH_PACKET_COMBINATIONS = "FETCH_PACKET_COMBINATIONS";
export const INSERT_PACKET_COMBINATION = "INSERT_PACKET_COMBINATION";
export const DELETE_PACKET_COMBINATION = "DELETE_PACKET_COMBINATION";
